Controllers/NobetciEczaneController.cs
using Microsoft.AspNetCore.Mvc;

namespace Eczane_Stok.Controllers
{
    public class NobetciEczaneController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
@using WebProjesi1.Utility
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Eczane Stok </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebProjesi1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Eczane Stok</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                       

                        @if (User.IsInRole(UserRoles.Role_Admin))
                        {

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="UrunTuru" asp-action="Index">Ürün Türü</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Urun" asp-action="Index">Ürün İşlemleri</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Satis" asp-action="Index">Satış İşlemi</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" target="_blank" asp-area="" asp-controller="NobetciEczane" asp-action="Index">Nöbetci Eczane</a>
                            </li>
                        }
                        @if (User.IsInRole(UserRoles.Role_Musteri))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Urun" asp-action="Index">Ürün Listesi</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" target="_blank" asp-area="" asp-controller="NobetciEczane" asp-action="Index">Nöbetci Eczane</a>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">İletişim</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Eczane Stok - <a asp-area="" asp-controller="Home" asp-action="Privacy">İletişim</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>